### ISSUE TITLE
found one issue

### ISSUE THREAD

**Issue by BlacknGoldy** [Doxthehuman/QBCore-Nopixel-Inspired-Police-Garage#3]
Hi,
thank you for your sharing...
i found one issue.
when someone taking the police car out and when he gonna deliver the car to the npc with qb-target , if someone else take the car and driver it, car will only be invisible for that person(despawner) and the other guy can still have the car and driver it and will be invisible for everyone. others can hear the car sounds only. hope you can reslove it . :)

**Comment by Doxthehuman** [comment]
Can anyone confrim this?

**Comment by RaMiNZer0** [comment]
yes i have same issue, i uploaded a video so you can see ...  https://streamable.com/xj3q37

**Comment by Doxthehuman** [comment]
Did some changes should be fixed. lmk if it's still happening or not

**Comment by BlacknGoldy** [comment]
nope now is like if someone is in the car cant restore the car. and after coming out of the car is buggy its says vehicle stored but still vehicle is out.

**Comment by Doxthehuman** [comment]
hmmm weird try this one should be fix
